package model;
import java.util.ArrayList;

public class Playlist{

    private String name;
    private ArrayList<Audio> audios;

    public Playlist(String name){
        this.name = name;
        this.audios = new ArrayList<Audio>();
    }

    public Audio searchSongInArrayList(String name, Artist producer) {
        boolean isFound = false;
        Audio audioFounded = null;
        for (int i = 0; i < audios.size() && !isFound; i++) {
            if (audios.get(i).getName().equalsIgnoreCase(name) && producer.searchSongInArrayList(name) != null) {
                audioFounded = audios.get(i);
                isFound = true;
            }
        }
        return audioFounded;
    }

    public Audio searchPodcastInArrayList(String name, ContentProducer producer) {
        boolean isFound = false;
        Audio audioFounded = null;
        for (int i = 0; i < audios.size() && !isFound; i++) {
            if (audios.get(i).getName().equalsIgnoreCase(name) && producer.searchPodcastV2(name) != null) {
                audioFounded = audios.get(i);
                isFound = true;
            }
        }
        return audioFounded;
    }

    public void addAudio(Audio audio) {
        audios.add(audio);
    }

    public String share(){
        //This is a non functional method temporarily, for the next requirements, the function is being capable of share a playlist, by the id code
        //Generated by the matrix.
        return name;
    }

    public String gettName(){
        return name;
    }

    public void setPlaylistName(String name){
        this.name = name;
    }
    
}
